### ISSUE TITLE
A pip installer for guacamol_baselines?

### ISSUE THREAD

**Issue by UnixJunkie** [BenevolentAI/guacamol_baselines#13]
This repository is a benchmark: people are supposed to be able to run it repeatably for years to come...
I wonder if providing a VM image with guacamol + guacamol_baselines properly co-installed
wouldn't be the best solution in the long run.

**Comment by JoshuaMeyers** [comment]
Hey @UnixJunkie, thanks for the suggestion. We provide a `Dockerfile` that allows you to recreate the environment in which the baselines were run, for `guacamol_baselines` this includes the exact versions of all dependencies.

For benchmarking your own models you only need to install `guacamol` from PyPI (version `0.5.4` will be released today)!

A pip installer for `guacamol_baselines` doesn't really make sense since baselines contains many implementations of baseline models, the underlying guacamol library is, however, pip installable.

**Comment by UnixJunkie** [comment]
Ok, thanks a lot for the detailed explanations.
